steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "*.html", "gs://www.aikibudoofdenver.com/"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "img/*.jpeg", "gs://www.aikibudoofdenver.com/img/"]